### ISSUE TITLE
NCDNS QT GUI that incorporates everything required to run NCDNS modules and DNSSEC modules

### ISSUE THREAD

**Issue by Gapcoin1** [namecoin/meta#70]
**Is your feature request related to a problem? Please describe.**

Sort of, it would aid adoption a lot faster and help maintaining websites easier........

**Describe the solution you'd like**

I would like to have a NCDNS QT GUI that incorporates all the NCDNS modules required to Ping the Namecoin Blockchain.

And if extra installation modules are needed to run a Required parts checklist of the things required to Run NCDNS to resolve .Bit domains and a different checklist for resolving regular Domains.   (Not sure if that is part of Namecoins goal resolving other Domains not very important to me personally however)

**Describe alternatives you've considered**

I have considered the grouping all the DNS Server into a QT GUI would also help the future step of full integration into Namecoin-Core GUI once all the bugs are worked on NCDNS GUI and Full-Time maintainer!

**Additional context**

Starting this process will help drive the .Bit DNS eco-system as all servers are Linux Based, but most all users are Windows based and require GUI's.  Making a Linux GUI will drastically help Windows users maintain their own websites and help troubleshooting and development easier.  Simplifying the required processes into 1 QT GUI.

Just as Bitcoin incorporated alot of current available software technologies into 1 project NCDNS should Port all the DNSSEC and .Bit DNS into 1 QT GUI project that is meant to run Parallel to Namecoin-Core QT GUI.

**Comment by JeremyRand** [comment]
I'm not sure I understand what functionality you're asking for.  ncdns doesn't have a GUI, since it's a DNS server; the only interaction the user will usually have with it is via tools like `q` and `dig`.  Are you talking about the ncdns Windows installer?  Or are you talking about a GUI for starting/stopping the ncdns service?  Or something else?

(Moving this issue to the Meta repo, which is the right place for suggestions for new projects.)

**Comment by Gapcoin1** [comment]
I thought it through more.  However I am counting on you to be the Technical Expert....of Namecoin Specialists.

After more upstream Logic Circuits, it would be Required to have 2 separate QT GUI's.  

**1)  For Users called NCDNS .Bit Resolver QT GUI or something ect........that could possibly be incorporated into Namecoin-Core in the future.**

**2)  A NCDNS QT GUI for Website Developers with a Automated Checklist for Required Items and Suggested Items require for different NCDNS Functionality Possibilities.**
 
.A) NCDNS Developer QT GUI to act as a sort of PGP holding the .Bit GUI for TLS Certificates and Developer PGP signing keys as well as holding the expiry dates.  

.B) NCDNS Developer QT could be closed after maintaining and updating TLS certs for .Bit domains.  And use the NCDNS Resolver QT GUI without exposing keys from needing to run all the time. 

.C)  Basically dump as much possible functionality into a Developer QT GUI with an Automated checklist that a Website Developer would need to run their own .Bit Website for resolution.  Even dump in a type of "Unbound" Functionality with multiple choices for DNS Resolvers  (I personally don't know everything required as I don't operate any websites).

.D)  Windows users will probably Require a QT GUI Resolver anyway to browse .Bit websites.  Creating 2 Branches for it with 1 being basic with possible dimensions into Namecoin-Core and another strictly like a NCDNS Developer QT GUI.


It's just the idea.  If it's possible I don't know.  But I just know it will be difficult for new .Bit developers to spend time learning each part individually if they are not expert already.  At least a Automated Checklist would help with a lot of things.

**Comment by JeremyRand** [comment]
> **1) For Users called NCDNS .Bit Resolver QT GUI or something ect........that could possibly be incorporated into Namecoin-Core in the future.**

What exactly is this GUI supposed to do, which isn't already done by ncdns-nsis?

> **2) A NCDNS QT GUI for Website Developers with a Automated Checklist for Required Items and Suggested Items require for different NCDNS Functionality Possibilities.**

Can you give concrete examples of "required items" and "suggested items"?  This sounds similar to something that I think we have NLnet funding for, but it's hard to tell since you're not giving specifics.

> .A) NCDNS Developer QT GUI to act as a sort of PGP holding the .Bit GUI for TLS Certificates and Developer PGP signing keys as well as holding the expiry dates.

I'm not convinced that we need Namecoin to provide a GUI for creating TLS certificates.  All Namecoin does is create a CA of a slightly unusual form.  Once you've created that CA, you can use it to issue certs using whatever non-Namecoin certificate tooling you like.  I assume there exist GUI tools for this (though I've never needed them).  PKI setups are diverse; it's not reasonable to expect Namecoin to make a Namecoin-specific GUI tool that handles all PKI use cases, when none of those use cases are Namecoin-specific.

Are you specifically asking for a GUI tool to generate the CA that has an unusual form?  Like, I guess maybe we could do that, but is that really useful, given that it's trivial to do from a terminal, and the resulting CA would be used by non-Namecoin tooling?

> .B) NCDNS Developer QT could be closed after maintaining and updating TLS certs for .Bit domains. And use the NCDNS Resolver QT GUI without exposing keys from needing to run all the time.

I should note here that one of the advantages of using non-Namecoin-specific tooling for handling certs is that you can easily use HSM's or similar isolation methods, so your private keys don't have to touch the machine that's displaying your GUI.

> .C) Basically dump as much possible functionality into a Developer QT GUI with an Automated checklist that a Website Developer would need to run their own .Bit Website for resolution. Even dump in a type of "Unbound" Functionality with multiple choices for DNS Resolvers (I personally don't know everything required as I don't operate any websites).

Again -- what example items would be on this checklist?  What is this "Unbound Functionality" supposed to do?

> .D) Windows users will probably Require a QT GUI Resolver anyway to browse .Bit websites. Creating 2 Branches for it with 1 being basic with possible dimensions into Namecoin-Core and another strictly like a NCDNS Developer QT GUI.

Windows users can already browser .bit websites without a Qt GUI for ncdns.  I don't understand what you want this GUI to do.

> It's just the idea. If it's possible I don't know. But I just know it will be difficult for new .Bit developers to spend time learning each part individually if they are not expert already. At least a Automated Checklist would help with a lot of things.

Running a website can be hard.  It can require learning things.  Many of which are very much outside the scope of Namecoin.  We're happy to try to make Namecoin as easy as possible to use, but we have to place some limits on scope.

**Comment by Gapcoin1** [comment]
Yes, I agree with you running a website will need to be specialized and probably have to wait till Namecoin .Bit domains become a lot more popular and they will direct the flow they need in the future.  I will go back to lurking.  Thanks

However, I do like the Automated Checklist as that is what I thought I would need from a Zero Knowledge base to use NCDNS and Namecoin Blockchain for DNS and Tor .Onion for hosting my own website from Home for further Decentralization!

https://tor-relay.co/ 

Provides the Automated Config options for Tor Relays. I read an article of so called bad Tor Exit actors flooding Tor.  So the Tor Devs. have no real desire to grow Tor unchecked as they ban these new Exit Relays if their Contact info is not accurate. 

So not sure how much luck Namecoin will really have working with Tor Browser overall.  I don't think Tor People want it to become anything more than a "Privacy Project".  Namecoin .Bit would make Tor the largest Platform WorldWide Possibly. 

In which case Namecoin .Bit hosting would need to help run their own Tor Exit Nodes and grow together.  I contacted Tor but not heard back about this scenario in the future in another mass censorship event which will come soon.

https://tor-relay.co/ In which case Namecoin should be ready to provide this Form to .Bit website Developers.

But they might have to figure it out on their own.  But it seems like Tor does not want to make it easier for people to know why they are deleting Tor Relays left and right. 

I can already imagine the Next Wikileaks or Facebook being run out of a Garage or Workshop Like Home Brewed Bitcoin Miner Farms, except running High Tech Namecoin .Bit Website Hosting!

That is where I was imagining the GUI and Automated Checklist for Non-Technical easy setup and to maintain.

But I am not Qualified to produce what would be desired in such a checklist other than everything Required.  Of which I am not a Specialist of DNS or Websites.

I will try to learn more before speaking again.

Either Way it's inevitable, the Homegrown .Bit Website Hosting Farm using High Tech Servers for hosting others .Bit websites!

Thanks
